### ISSUE TITLE
libvirt backend frequently gives traceback exception when domain gets destroyed

### ISSUE THREAD

**Issue by epienbroek** [virt-who/virt-who#34]
On my local machine I'm doing platform development of RHEL machines using the tool Vagrant. With this tool I'm able to quickly create/destroy VM's and have them provisioned. As we're using RHEL in our company we have to use Katello for software and subscription management. To allow proper administration of the host-to-guest mappings we're using virt-who to monitor the libvirt/KVM host and have all changes reported to Katello automatically.

We've installed virt-who on the Katello machine (which is a VM running on a KVM host). Using an exchanged ssh keypair we've authorized virt-who on the Katello machine to communicate with the libvirt/KVM host (thus we're using a remote libvirt connection).

The Katello VM is running RHEL 7.2. The libvirt/KVM host is running Fedora 24.

In testing we've noticed that virt-who frequently starts to give traceback exceptions whenever a libvirt domain (in other words: a VM) gets destroyed.

Here's what happens according to syslog/journalctl:
```
2016-09-19 13:40:19,469 [virtwho.env_cmdline ERROR] Libvirtd-1(11096):MainThread @virt.py:run:379 - Virt backend 'env/cmdline' fails with exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtwho/virt/virt.py", line 372, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 195, in _run
    if self.virt.isAlive() != 1:
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4095, in isAlive
    if ret == -1: raise libvirtError ('virConnectIsAlive() failed', conn=self)
libvirtError: invalid connection pointer in virConnectIsAlive
2016-09-19 13:40:19,469 [virtwho.env_cmdline INFO] Libvirtd-1(11096):MainThread @virt.py:run:392 - Waiting 60 seconds before retrying backend 'env/cmdline'
```

The logfile /var/log/rhsm/rhsm.log contains this:
```
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: Traceback (most recent call last):
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 245, in _listDomains
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: domain = self.virt.lookupByName(domainName)
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4222, in lookupByName
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: libvirtError: Domein niet gevonden: geen domein met overeenkomende naam 'puppet_conf_upstreamable_dev01'
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: Traceback (most recent call last):
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4855, in _dispatchDomainEventCallbacks
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: cb(self, virDomain(self, _obj=dom), event, detail, opaque)
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 220, in _callback
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: report = self._get_report()
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 226, in _get_report
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: return HostGuestAssociationReport(self.config, self._getHostGuestMapping())
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 295, in _getHostGuestMapping
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: guestIds=self._listDomains(),
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 250, in _listDomains
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: raise VirtError(str(e))
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: virtwho.virt.virt.VirtError: Domein niet gevonden: geen domein met overeenkomende naam 'puppet_conf_upstreamable_dev01'
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: Traceback (most recent call last):
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4855, in _dispatchDomainEventCallbacks
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: cb(self, virDomain(self, _obj=dom), event, detail, opaque)
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 220, in _callback
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: report = self._get_report()
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 226, in _get_report
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: return HostGuestAssociationReport(self.config, self._getHostGuestMapping())
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 291, in _getHostGuestMapping
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: Hypervisor.HYPERVISOR_TYPE_FACT: self.virt.getType(),
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4015, in getType
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: if ret is None: raise libvirtError ('virConnectGetType() failed', conn=self)
sep 19 13:40:18 katello.infoplus-local.ris virt-who[11089]: libvirt.libvirtError: invalid connection pointer in virConnectGetType
sep 19 13:40:19 katello.infoplus-local.ris /usr/bin/virt-who[11089]: 2016-09-19 13:40:19,469 [virtwho.env_cmdline ERROR] Libvirtd-1(11096):MainThread @virt.py:run:379 - Virt backend 'env/cmdline' fails with exception:
                                                                     Traceback (most recent call last):
                                                                       File "/usr/lib/python2.7/site-packages/virtwho/virt/virt.py", line 372, in run
                                                                         self._run()
                                                                       File "/usr/lib/python2.7/site-packages/virtwho/virt/libvirtd/libvirtd.py", line 195, in _run
                                                                         if self.virt.isAlive() != 1:
                                                                       File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4095, in isAlive
                                                                         if ret == -1: raise libvirtError ('virConnectIsAlive() failed', conn=self)
                                                                     libvirtError: invalid connection pointer in virConnectIsAlive
sep 19 13:40:19 katello.infoplus-local.ris /usr/bin/virt-who[11089]: 2016-09-19 13:40:19,469 [virtwho.env_cmdline INFO] Libvirtd-1(11096):MainThread @virt.py:run:392 - Waiting 60 seconds before retrying backend 'env/cmdline'
sep 19 13:40:19 katello.infoplus-local.ris /usr/bin/virt-who[11089]: 2016-09-19 13:40:19,740 [virtwho.main DEBUG] MainProcess(11089):MainThread @executor.py:send_report:101 - Report for config "env/cmdline" sent
```

The message 'Domein niet gevonden: geen domein met overeenkomende naam ...' translates to 'Domain not found: no domain matching name ...'.

It looks like virt-who tries to look up details about the VM which was just destroyed, runs into a failure (as the VM was just destroyed) and drops the entire libvirt connection.

These exceptions are triggered by having one of the libvirt VM's destroyed (we're using 'vagrant destroy' for this). It doesn't happen every time a VM gets's destroyed, but it does happen quite frequently on my machine.

The issue can be reproduced with both virt-who-0.14-9.el7.noarch (RHEL 7.2) as well as virt-who-0.17-7.el7.noarch (RHEL 7.3 beta).

With further debugging I was able to pinpoint the exact location where the exception happens. This seems to be ```domain = self.virt.lookupByName(domainName)``` (https://github.com/virt-who/virt-who/blob/master/virtwho/virt/libvirtd/libvirtd.py#L240). At that point the ```self.virt.listDefinedDomains()``` call (one line earlier) has returned a list of libvirt domains which still includes the VM which was just destroyed.

Would it make sense to guard the ```domain = self.virt.lookupByName(domainName)``` call in a separate try/catch block and have 'No domain found with name' exceptions ignored?

**Comment by epienbroek** [comment]
I've just tried to implement the additional try/catch block which I suggested earlier. This change fixes the issue for me. The commit can be found at: https://github.com/epienbroek/virt-who/commit/3193d3b8e2b992122bbde253983be92dcf691443
If you're interested in applying it in virt-who, feel free to do so. If necessary I can create a PR for it

**Comment by rnovacek** [comment]
Thank you for your report. I've take the liberty to adjust your patch a little before committing:

https://github.com/virt-who/virt-who/commit/bf69582cf4eb0d6dee93ced4966dc1ae0e7af40e
